server:
  error:
    include-stacktrace: always
  port: ${SERVER_PORT}

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    database-change-log-table: changelog
    database-change-log-lock-table: changeloglock
    default-schema: ${DATASOURCE_SCHEMA}
    liquibase-schema: ${DATASOURCE_LIQUIBASE_SCHEMA}
    user: ${LIQUIBASE_USERNAME}
    password: ${LIQUIBASE_PASSWORD}
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_URL}
      client-id: ${KAFKA_CLIENT_ID}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  topic:
    finish-registration: ${KAFKA_TOPIC_FINISH_REGISTRATION}
    create-documents: ${KAFKA_TOPIC_CREATE_DOCUMENTS}
    send-documents: ${KAFKA_TOPIC_SEND_DOCUMENTS}
    send-ses: ${KAFKA_TOPIC_SEND_SES}
    credit-issued: ${KAFKA_TOPIC_CREDIT_ISSUED}
    application-denied: ${KAFKA_TOPIC_APPLICATION_DENIED}

feign:
  client:
    config:
      default:
        connectTimeout: ${FEIGN_CONNECT_TIMEOUT}
        readTimeout: ${FEIGN_READ_TIMEOUT}
        loggerLevel: ${FEIGN_LOG_LEVEL}

logging:
  level:
    ru.neoflex.deal: ${LOG_LEVEL}
    ru.neoflex.deal.feign: ${LOG_LEVEL}

application:
  url:
    conveyor: ${CONVEYOR_URL}