version: '3.9'
services:
  db_postgres:
    image: postgres:13.1
    container_name: db_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db_data/init.sql:/docker-entrypoint-initdb.d/init.sql

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    restart: on-failure
    image: bitnami/kafka:latest
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./prom_data/prometheus.yml
        target: /etc/prometheus/prometheus.yml

  ms-deal:
    restart: on-failure
    image: lexana/java-service:ms-deal
    container_name: ms-deal
    ports:
      - '8082:8082'
    env_file:
      - .env.ms-deal
    depends_on:
      - db_postgres
      - kafka
      - prometheus

  ms-conveyor:
    restart: on-failure
    image: lexana/java-service:ms-conveyor
    container_name: ms-conveyor
    ports:
      - "8081:8081"
    env_file:
      - .env.ms-conveyor
    depends_on:
      - prometheus

volumes:
  db_data: