version: '3.9'
services:
  db_postgres:
    image: postgres:13.1
    container_name: db_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db_data/init.sql:/docker-entrypoint-initdb.d/init.sql

  ms-deal:
    restart: on-failure
    image: lexana/java-service:gradle
    container_name: ms-deal
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    env_file:
      - .env
    depends_on:
      - db_postgres

#  zookeeper:
#    image: bitnami/zookeeper:latest
#    ports:
#      - '2181:2181'
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#
#  kafka:
#    image: bitnami/kafka:latest
#    ports:
#      - '9092:9092'
#    environment:
#      - KAFKA_BROKER_ID=1
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper

volumes:
  db_data: