version: "3.9"

services:
  ms-conveyor:
    build:
      context: .
      dockerfile: Dockerfile
    image: ms-conveyor
    container_name: ms-conveyor
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 150M